services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grip_invest
      MYSQL_USER: grip
      MYSQL_PASSWORD: grip_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    image: gripinvest-backend   # ✅ added
    environment:
      NODE_ENV: development
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET:-supersecretjwt}
      BCRYPT_ROUNDS: 10
      AI_MODE: ${AI_MODE:-local}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      COHERE_MODEL: ${COHERE_MODEL:-command}
      EMAIL_FROM: no-reply@gripinvest.local
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: grip
      MYSQL_PASSWORD: grip_pass
      MYSQL_DATABASE: grip_invest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    image: gripinvest-frontend   # ✅ added
    environment:
      VITE_API_BASE: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data:
